### ISSUE TITLE
Inventory management

### ISSUE THREAD

**Issue by mpkasp** [mpkasp/django-bom#12]
Each part revision to have inventory tracking including quantity and location (thanks @lcesero) of that quantity.
May be interesting to add seller inventory, similarly have a single field that can be updated

Let's discuss further before starting on this feature.

**Comment by DasBasti** [comment]
This is exactly what I need.

**Comment by ks156** [comment]
This is really a feature that I need as well. A few months ago I started implementing warehouses, but I didn't finish it yet (lack of time, as usual ...)

I have cleaned and rebased my local branch today (rebased on my master branch, which also contains the seller preference: see https://github.com/mpkasp/django-bom/pull/84). I will push this branch on my remote repo, so the change could be already accessible for tests and critics.

Here's how I imagine this implementation :
- Add the ability to create warehouses.
- Add the ability to put parts in warehouses (from the part management pages). 
- When parts are added to a warehouse, the price can be either calculated from the seller price (in that case, the preferred seller part), computed from the subparts, or set manually.
- On the part specifications, the estimated price would be split to display: 
   - The estimated price of parts that must be purchased
   - The price of parts that are in warehouses
   - The estimated total price (sum of the two prices above)
- The warehouse details that show the parts, quantity, unit price (or avg unit price if relevant), and total price of parts contained in the warehouse. 

Is it (roughly) how you imagined this feature @mpkasp @DasBasti ?

**Comment by mpkasp** [comment]
@ks156 lack of time, sounds familiar :) Thanks for putting these great thoughts together. Definitely sounds roughly how I imagined this feature. Here's some hopefully constructivev feedback:

> Add the ability to create warehouses.

Probably need all CRUD operations / views

> Add the ability to put parts in warehouses (from the part management pages).

Thinking about this UX & when a user would want to add parts to a warehouse. Probably a few scenarios:
1. They recceive a single order of a single part, probably easy to go to the part management page to add more parts to a warehouse
2. They receive an order of multiple parts (E.g. an electrical BOM of 20+ components). Probably some other faster method to import multiple parts from a single view would make more sense?
3. Also need to think about when parts move between warehouses, and removed from inventory.
Of course we could talk about part disposition, and combining parts into subassemblies instead of removing them, but we probably don't need to get that fancy for the initial implementation

>When parts are added to a warehouse, the price can be either calculated from the seller price (in that case, the preferred seller part), computed from the subparts, or set manually.

Sounds pretty good. Maybe a seller part could be selected from a list, and defaulted to preferred?

> On the part specifications, the estimated price would be split to display...

Cool!

> The warehouse details that show the parts, quantity, unit price (or avg unit price if relevant), and total price of parts contained in the warehouse.

I guess this is the "R" part of the Warehouse CRUD views. Sounds good to me. Did you consider the ability to update part quantity / price, move parts to different warehouses from here as well?


Generally, it'd be nice if the UI & UX of the inventory feature is out of the way if users decide not to use it, but in the right places if they do decide to..if that makes sense.

**Comment by mpkasp** [comment]
For now, I'm thinking this is a whole different product, possibly a great "sibling" product to IndaBOM. I'm willing to re-visit this in the future, but closing this for now.
