### ISSUE TITLE
Possible to create invalid part number classes

### ISSUE THREAD

**Issue by aaronbeekay** [mpkasp/django-bom#31]
Using the part class edit page (`/bom/settings/user/#indabom`), it's possible to create a part class that is 2 digits long: 

![image](https://user-images.githubusercontent.com/7378316/71785522-863af280-2fce-11ea-89ab-0fde02f85e9d.png)

It's possible to use the "add part" interface to create a part in this class:

![image](https://user-images.githubusercontent.com/7378316/71785534-a4085780-2fce-11ea-8801-cf259891fa47.png)

But if you try and add that part to another part's BOM, it doesn't work, and the UI spits out a confusing error:

![image](https://user-images.githubusercontent.com/7378316/71785544-cef2ab80-2fce-11ea-833a-be7e2c560afd.png)

I think:

* It should be clarified if part classes must be three digits
* If they must be three digits, the part class page should enforce that

**Comment by aaronbeekay** [comment]
P.S. Just found `django-bom` / `indabom` -- they're great! Just what I've been thinking about for a while. Would love to help out where I can.

**Comment by mpkasp** [comment]
Agreed, good catch @aaronbeekay . Would you like to take a stab at this one?

**Comment by aaronbeekay** [comment]
@mpkasp Sure - I will need to get a local install set up, but it’s a good excuse to do that anyway. I’ll try and do it this week.

**Comment by mpkasp** [comment]
Resolved in 67912e12da837dca6dcaee3db875e13f16d6113d
