### ISSUE TITLE
requirements.txt fails at mysqlclient -1.3.13

### ISSUE THREAD

**Issue by patrick-tyger1** [mpkasp/django-bom#45]
Following the **Start from Scratch: Use as a standalone Django Project**. I've tried on both Ubuntu 18.04 and 20.04

`Collecting mysqlclient==1.3.13
  Downloading mysqlclient-1.3.13.tar.gz (90 kB)
     |████████████████████████████████| 90 kB 5.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/patrick/.virtualenvs/django-bom01/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wjlk8b4m/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wjlk8b4m/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-wjlk8b4m/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-wjlk8b4m/mysqlclient/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wjlk8b4m/mysqlclient/setup.py", line 18, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-wjlk8b4m/mysqlclient/setup_posix.py", line 53, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-wjlk8b4m/mysqlclient/setup_posix.py", line 28, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by mpkasp** [comment]
Have you made sure mysql_config is installed on your Ubuntu instance? Check out [this stackoverflow](https://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface) and let me know if that resolves your issue. If so maybe I should add that to the install steps...

**Comment by patrick-tyger1** [comment]
Still no luck, but reading through many of the posts about this issue, the problem is likely due to a problem on my end. Unless you want to keep open for adding additional install instructions, this can be closed

**Comment by ambroiseA** [comment]
Hi,

I made the install on a raspberry PI (raspbian), I had the same issue. I had to install following packages:

`sudo apt-get update`
`sudo apt-get install mariadb-server-10.0 libmariadbclient-dev default-libmysqlclient-dev`

Hope this help

**Comment by mpkasp** [comment]
Thanks @ambroiseA ! Ill close this now.
