### ISSUE TITLE
Add manufacturer part and seller part during parts/boms csv import

### ISSUE THREAD

**Issue by ks156** [mpkasp/django-bom#55]
It would be nice to be able to import the manufacturer and seller informations during the CSV parts and bom import.

**Comment by mpkasp** [comment]
I agree! I don't have the time at the moment but feel free to submit a pull request.

**Comment by ks156** [comment]
Yes of course I would do it (once I also find the time to implement this 😃)

**Comment by mpkasp** [comment]
Merged in via 60c29b1621c18f99b9b807155d70b3fb5a0ef53f
