### ISSUE TITLE
OperationalError when creating an Organization

### ISSUE THREAD

**Issue by schoettl** [mpkasp/django-bom#6]
Is this a known error? Or a mistake in the name `auth_user__old` maybe?

```
OperationalError at /admin/bom/organization/add/
no such table: main.auth_user__old
Request Method:	POST
Request URL:	http://127.0.0.1:8000/admin/bom/organization/add/?_to_field=id&_popup=1
Django Version:	2.1.3
Exception Type:	OperationalError
Exception Value:	
no such table: main.auth_user__old
Exception Location:	/tmp/mysite/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 296
Python Executable:	/tmp/mysite/bin/python
Python Version:	3.7.1
Python Path:	
['/tmp/mysite/mysite',
 '/tmp/mysite/lib/python37.zip',
 '/tmp/mysite/lib/python3.7',
 '/tmp/mysite/lib/python3.7/lib-dynload',
 '/usr/lib64/python3.7',
 '/usr/lib/python3.7',
 '/tmp/mysite/lib/python3.7/site-packages']
Server time:	Thu, 3 Jan 2019 16:46:25 +0000
```

**Comment by mpkasp** [comment]
Weird, I assume you went to http://127.0.0.1:8000/bom/admin/bom/organization/add/ and filled in the form and selected "save"? 

I didn't get any kind of error when doing the above. Maybe you can give more steps to reproduce?

**Comment by schoettl** [comment]
Hm, yes, that is the same URL I used when I (still) get the error.

First, I logged in successfully at http://127.0.0.1:8000/admin/ with the super user account I created during setup.

I just tried to migrate again:

```
Operations to perform:
  Apply all migrations: admin, auth, bom, contenttypes, sessions, social_django
Running migrations:
  No migrations to apply.
```

**Comment by mpkasp** [comment]
The other thing that's odd is it looks like the table is associated with a `main` package? 

Check this out - are you using sqlite as a backend? 

https://stackoverflow.com/questions/53637182/django-no-such-table-main-auth-user-old

**Comment by schoettl** [comment]
Thanks mpkasp! I just upgradet Django from 2.1.3 to 2.1.5 and now creating organizations works.
